from odoo import api, fields, models,_from odoo.exceptions import UserError,ValidationErrorclass PosSession(models.Model):    _inherit = 'pos.session'    payment = fields.Many2one(comodel_name="pos.payment.method", string="Payment", required=False, )    def action_pos_session_validate(self):        self._check_pos_session_balance()        if self.config_id.cash_control and (not self.cash_register_id or not self.cash_register_id.cashbox_end_id):            raise ValidationError(_('Please Set Closing Balance!'))        for session in self:            if session.config_id.cash_control == True:                # if session.cash_register_difference:                payment_method = self.env['pos.payment.method'].search(                    [('id', 'in', session.payment_method_ids.ids), ('is_cash_count', '=', True)], limit=1)                session.payment=payment_method.id                if (payment_method.cash_journal_id.loss_account_id.total_balance + session.cash_register_difference) > payment_method.cash_journal_id.loss_account_id.limit_balance:                    raise ValidationError('This Account Reached Max Limit')        return self.action_pos_session_close()